<?php
/**
 * Yireo Custsize
 *
 * @package     Yireo_Custsize
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2011 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>

<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:100%;"><h3 class="icon-head head-tag"><?php echo $this->__('Customer Fields Overview'); ?></h3></td>
	</tr>
</table>
</div>

<div class="entry-edit" id="custsize-fields">
    <?php echo $this->getGridHtml() ?>
</div>

<script type="text/javascript">
var fieldsForm = new varienForm('custsize_fields_form');
function doSubmit() {
    fieldsForm.submit();
    return true;
}
</script>
