<?php
/**
 * Yireo Commons - Footer template
 *
 * @package     Yireo_Custsize
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2013 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<div class="yireo-footer">
    <p>
        <a href="http://www.yireo.com/" target="_new">Yireo</a>
        <?php echo $this->getTitle(); ?> <?php echo $this->getVersion(); ?>
    </p>
</div>

<style>
div.yireo-footer { text-align: center; margin: 30px; }
div.yireo-footer-inner p { font-size:90%; color:#575757; padding-top:20px; }
div.yireo-footer-inner img { display:inline;padding-left:5px; }
</style>
