<?php
/**
 * Yireo Custsize
 *
 * @author Yireo
 * @package Custsize
 * @copyright Copyright 2014
 * @license Yireo EULA (www.yireo.com)
 * @link http://www.yireo.com
 */
?>
<?php
/**
 * Product listing
 *
 * @see Yireo_Custsize_Block_Admin_Field_Edit
 */

$field = $this->getField();
?>
<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:40%;"><h3 class="icon-head head-tag"><?php echo $this->getTitle(); ?></h3></td>
        <td class="formbuttons" align="right">
            <?php echo $this->getChildHtml('back_button'); ?>
            <?php if($field->getFieldId() > 0) echo $this->getChildHtml('delete_button'); ?>
            <?php echo $this->getChildHtml('save_button'); ?>
        </td>
	</tr>
</table>
</div>

<div id="alert_messages_block"><?php echo $this->getMessageHtml() ?></div>

<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="custsize_edit_form" enctype="multipart/form-data">
<div class="entry-edit">
<div class="entry-edit-head">
    <h4><?php echo $this->__('Edit'); ?></h4>
</div>
<div class="fieldset">
<table cellspacing="0" class="form-list">
    <tbody>
        <tr class="headings">
            <td class="label">
                <label for="field_id"><?php echo Mage::helper('custsize')->__('ID')?></label>
            </td>
            <td class="value">
                <?php echo $field->getFieldId(); ?>
                <input type="hidden" name="field[field_id]" id="field_id" value="<?php echo $field->getFieldId(); ?>" />
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label for="label"><?php echo Mage::helper('custsize')->__('Label')?></label>
            </td>
            <td class="value">
                <input type="text" name="field[label]" id="label" value="<?php echo htmlentities($field->getLabel()); ?>" class="input-text required-entry" />
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label for="description"><?php echo Mage::helper('custsize')->__('Description')?></label>
            </td>
            <td class="value">
                <input type="text" name="field[description]" id="description" value="<?php echo htmlentities($field->getDescription()); ?>" class="input-text" />
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label for="fieldset"><?php echo Mage::helper('custsize')->__('Fieldset')?></label>
            </td>
            <td class="value">
                <select name="field[fieldset]" id="fieldset">
                    <?php foreach($this->getFieldsets() as $fieldset) { ?>
                    <?php $selected = ($field->getFieldset() == $fieldset->getTag()) ? 'selected' : ''; ?>
                    <option value="<?php echo $fieldset->getTag() ?>" <?php echo $selected ?>><?php echo $fieldset->getLabel() ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label for="unit"><?php echo Mage::helper('custsize')->__('Unit')?></label>
            </td>
            <td class="value">
                <select name="field[unit]" id="unit">
                    <?php foreach($this->getUnits() as $value => $label) { ?>
                    <?php $selected = ($field->getUnit() == $value) ? 'selected' : ''; ?>
                    <option value="<?php echo $value ?>" <?php echo $selected ?>><?php echo $label ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label><?php echo Mage::helper('custsize')->__('Enabled')?></label>
            </td>
            <td class="value">
                <?php echo $this->getYesno('enabled', $field->getEnabled()); ?>
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label><?php echo Mage::helper('custsize')->__('Required')?></label>
            </td>
            <td class="value">
                <?php echo $this->getYesno('required', $field->getRequired()); ?>
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label><?php echo Mage::helper('custsize')->__('Dashboard')?></label>
            </td>
            <td class="value">
                <?php echo $this->getYesno('dashboard', $field->getDashboard()); ?>
                <br/><small><?php echo Mage::helper('custsize')->__('[Optional] Only used for custom development.'); ?></small>
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label for="marker"><?php echo Mage::helper('custsize')->__('Marker')?></label>
            </td>
            <td class="value">
                <input type="text" name="field[marker]" id="marker" value="<?php echo htmlentities($field->getMarker()); ?>" class="input-text" />
                <br/><small><?php echo Mage::helper('custsize')->__('[Optional] Only used for custom development.'); ?></small>
            </td>
        </tr>
        <tr class="headings">
            <td class="label">
                <label for="ordering"><?php echo Mage::helper('custsize')->__('Ordering')?></label>
            </td>
            <td class="value">
                <input type="text" name="field[ordering]" id="ordering" value="<?php echo (int) $field->getOrdering(); ?>" class="input-text" />
            </td>
        </tr>
    </tbody>
</table>
</div>
</div>

<?php echo $this->getBlockHtml('formkey')?>
</form>

<script type="text/javascript">
//<![CDATA[
var custsizeForm = new varienForm('custsize_edit_form');
</script>
