<?php
/**
 * Yireo Custsize
 *
 * @package     Yireo_Custsize
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$profile = $this->getProfile();
?>
<div class="page-title">
    <h1><?php echo $this->__('Please confirm'); ?></h1>
</div>

<p><?php echo $this->__('Are you sure you want to delete this profile?'); ?></p>

<form action="<?php echo $this->getDeleteUrl()?>" method="post" id="form-validate">
    <?php echo $this->getBlockHtml('formkey')?>
    <button type="submit" title="<?php echo $this->__('Delete') ?>" class="button"><span><span><?php echo $this->__('Delete') ?></span></span></button>
</form>
        
<p class="back-link"><a href="<?php echo $this->getUrl('custsize/index/profiles') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
