<?php
/**
 * Yireo Custsize
 *
 * @package     Yireo_Custsize
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$profile = $this->getProfile();
?>
<div class="page-title">
    <h1><?= $this->getTitle(); ?></h1>
</div>
<?= $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?= $this->getSaveUrl()?>" method="post" id="form-validate">
    <?= $this->getBlockHtml('formkey')?>
    <div class="fieldset">
        <h2 class="legend"><?= $this->__('Basic Information') ?></h2>
        <?php $basicFields = $this->getFieldsFromFieldset('basic'); ?>
        <ul class="form-list">
            <li>
                <label for="name" class="required">
                    <?= $this->__('Name')?>
                </label>
                <div class="input-box">
                    <input type="text" name="profile[name]" id="name" 
                        value="<?= $this->htmlEscape($profile->getData('name')) ?>" 
                        title="<?= $this->__('Name') ?>" class="input-text" />
                </div>
            </li>
            <li>
                <label for="description">
                    <?= $this->__('Description')?>
                </label>
                <div class="input-box">
                    <input type="text" name="profile[description]" id="description" 
                        value="<?= $this->htmlEscape($profile->getData('description')) ?>" 
                        title="<?= $this->__('Description') ?>" class="input-text" />
                </div>
            </li>
            <?php foreach($basicFields as $field): ?>
            <li>
                <?php $class = array(); ?>
                <?php if($field->getData('required') == 1) $class[] = 'required'; ?>
                <label for="field<?= $field->getId()?>" class="<?= implode($class)?>">
                    <?php if($field->getData('required') == 1) : ?><em>*</em></em><?php endif; ?>
                    <?= $this->__($field->getLabel())?>
                </label>
                <?php if($field->getDescription()): ?><br/><em><?= $field->getDescription(); ?></em><?php endif; ?>
                <div class="input-box">
                    <?php $class = array('input-text'); ?>
                    <?php if($field->getData('required') == 1) $class[] = 'required-entry'; ?>
                    <input type="text" name="field[<?= $field->getId()?>]" id="<?= $field->getId()?>" 
                        value="<?= $this->htmlEscape($profile->getData('field'.$field->getId())) ?>" 
                        title="<?= $this->__($field->getLabel()) ?>" class="<?= implode(' ', $class); ?>" />
                    <?php if($field->getUnit()): ?><small>[<?= $field->getUnit(); ?>]</small><?php endif; ?>
                </div>
            </li>
            <?php endforeach; ?>
            <li>
                <label for="default"><?= $this->__('Default'); ?></label>
                <div class="input-box">
                    <input type="checkbox" name="profile[default]" value="1" <?php if($profile->getData('default')) echo 'checked' ?> />
                </div>
            </li>
        </ul>
    </div>

    <?php foreach($this->getFieldsets() as $fieldset) : ?>
    <?php if($fieldset->getTag() == 'basic') continue; ?>
    <div class="fieldset">
        <h2 class="legend"><?= $this->__($fieldset->getLabel()) ?></h2>
        <?php $fields = $this->getFieldsFromFieldset($fieldset->getTag()); ?>
        <?php if($fields->count() > 0) : ?>
        <table width="100%">
            <?php foreach($fields as $field): ?>
            <tr>
                <?php $class = array(); ?>
                <?php if($field->getData('required') == 1) $class[] = 'required'; ?>
                <td>
                    <h3><?= $field->getMarker() ?></h3>
                </td>
                <td>
                    <label for="field<?= $field->getId()?>" class="<?= implode($class)?>">
                        <?php if($field->getData('required') == 1) : ?><em>*</em></em><?php endif; ?>
                        <?= $this->__($field->getLabel())?>
                    </label>
                    <?php if($field->getDescription()): ?><br/><em><?= $field->getDescription(); ?></em><?php endif; ?>
                </td>
                <td class="input-box">
                    <?php $class = array('input-text'); ?>
                    <?php if($field->getData('required') == 1) $class[] = 'required-entry'; ?>
                    <input type="text" name="field[<?= $field->getId()?>]" id="field<?= $field->getId()?>" 
                        value="<?= $this->htmlEscape($profile->getData('field'.$field->getId())) ?>" 
                        title="<?= $this->__($field->getLabel()) ?>" class="<?= implode(' ', $class); ?>" />
                </td>
                <td>
                    <?php if($field->getUnit()): ?><small>[<?= $field->getUnit(); ?>]</small><?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php else: ?>
        <p><?= $this->__('No fields found'); ?></p>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>

    <div class="buttons-set">
        <p class="required"><?= $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?= $this->getUrl('custsize/index/profiles') ?>"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
        <button type="submit" title="<?= $this->__('Save') ?>" class="button"><span><span><?= $this->__('Save') ?></span></span></button>
    </div>
</form>

<form action="<?= $this->getConfirmdeleteUrl()?>" method="post" id="form-validate">
    <div style="float:right; padding-top:5px;">
        <?= $this->getBlockHtml('formkey')?>
        <?php if($profile->getProfileId() > 0) : ?>
        <button type="submit" title="<?= $this->__('Delete') ?>" class="button"><span><span><?= $this->__('Delete') ?></span></span></button>
        <?php endif; ?>
    </div>
</form>

<script>
    var dataForm = new VarienForm('form2-validate', true);
</script>