<?php
/**
 * Yireo Custsize
 *
 * @package     Yireo_Custsize
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2011 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$profiles = $this->getProfiles();
$defaultProfile = $this->getDefaultProfile();
$otherProfiles = $this->getOtherProfiles();
$dashboardFields = $this->getDashboardFields();

?>
<style>
td.name {font-weight: bold;}
</style>

<div class="dashboard">
<div class="box-account box-info">
    <div class="box-head">
        <h2><?php echo $this->__('Size Profiles') ?></h2>
    </div>

    <div class="col2-set">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Size Profile') ?></h3>
                </div>
                <div class="box-content">
                    <?php if(!empty($defaultProfile)): ?>
                    <table width="100%">
                    <tbody>
                        <tr>
                            <td class="name"><?php echo $this->__('Name')?></td>
                            <td class="value"><?php echo $defaultProfile->getName(); ?></td>
                        </tr>
                        <tr>
                            <td class="name"><?php echo $this->__('Description')?></td>
                            <td class="value"><?php echo $defaultProfile->getDescription(); ?></td>
                        </tr>
                        <?php foreach($dashboardFields as $dashboardField) : ?>
                        <tr>
                            <td class="name"><?php echo $dashboardField->getLabel(); ?></td>
                            <td class="value"><?php echo $defaultProfile->getData('field'.$dashboardField->getId()); ?></td>
                        </tr>
                        <?php endforeach; ?>
                        <tr>
                            <td colspan="2"><a href="<?php echo $this->getEditUrl($defaultProfile) ?>"><?php echo $this->__('Edit'); ?></a></td>
                        </tr>
                    </tbody>
                    </table>
                    <?php else: ?>
                        <p><?php echo $this->__('No default profile available'); ?></p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Additional Size Profiles') ?></h3>
                </div>
                <div class="box-content">
                    <?php if(!empty($otherProfiles)): ?>
                    <table width="100%">
                    <tbody>
                        <?php foreach($otherProfiles as $profile): ?>
                        <tr>
                            <td><?php echo $profile->getName(); ?></td>
                            <td><a href="<?php echo $this->getEditUrl($profile) ?>"><?php echo $this->__('Edit'); ?></a></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    </table>
                    <?php else: ?>
                        <p><?php echo $this->__('No additional profiles available'); ?></p>
                        <p><a href="<?php echo $this->getNewUrl() ?>"><?php echo $this->__('Click here to create a new profile'); ?></a></p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
