<?php
/**
 * Yireo Custsize
 *
 * @package     Yireo_Custsize
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2011 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$profile = $this->getProfile();
?>
<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:40%;"><h3 class="icon-head head-tag"><?php echo $this->__('Delete Customer Size Profile'); ?></h3></td>
        <td class="formbuttons" align="right">
            <?php echo $this->getChildHtml('delete_button'); ?>
        </td>
	</tr>
</table>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Confirmation'); ?></h4>
    </div>
    <div class="fieldset">
        <p><?php echo $this->__('Are you sure you want to delete this profile?') ?></p>
    </div>
</div>
